name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GitHub Docker Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/nextcloud-backup:latest ./k8s

      # Push the Docker image
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/nextcloud-backup:latest